# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 08:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='design',
            new_name='creativity',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=6000),
        ),
    ]
